DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS skills;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  fullname TEXT NOT NULL,
  address TEXT NOT NULL,
  email TEXT NOT NULL,
  phone INTEGER NOT NULL
);

CREATE TABLE skills (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  level TEXT NOT NULL
);
